MarketPlace.Presentation/Areas/Seller/Controllers/SellerWalletController.cs
using MarketPlace.Application.DTOs.SellerWallet;
using MarketPlace.Application.InterfaceServices;
using MarketPlace.Presentation.PresentationExtensions;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Presentation.Areas.Seller.Controllers
{
    public class SellerWalletController : SellerBaseController
    {
        #region constructor

        private readonly ISellerWalletService _sellerWalletService;
        private readonly ISellerService _sellerService;

        public SellerWalletController(ISellerWalletService sellerWalletService, ISellerService sellerService)
        {
            _sellerWalletService = sellerWalletService;
            _sellerService = sellerService;
        }

        #endregion

        #region index

        [HttpGet("seller-wallet")]
        public async Task<IActionResult> Index(FilterSellerWalletDTO filter)
        {
            filter.TakeEntity = 5;
            var seller = await _sellerService.GetLastActiveSellerByUserId(User.GetUserId());
            if (seller == null) return NotFound();
            filter.SellerId = seller.Id;
            return View(await _sellerWalletService.FilterSellerWallet(filter));
        }

        #endregion
    }
}

MarketPlace.Presentation/Areas/Seller/Views/SellerWallet/Index.cshtml
@using MarketPlace.Application.Utilities
@using MarketPlace.Application.Extensions
@model MarketPlace.Application.DTOs.SellerWallet.FilterSellerWalletDTO
@{
    ViewData["Title"] = "کیف پول فروشنده";
}



<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>@ViewData["Title"]</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("SellerSidebar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>@ViewData["Title"] </h3>
                            <form method="get" asp-area="Seller" asp-controller="SellerWallet" asp-action="Index" id="filter-form">
                                <input type="hidden" asp-for="PageId" />
                                <div class="table-responsive">
                                    @if (Model.SellerWallets != null && Model.SellerWallets.Any())
                                    {
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>شناسه</th>
                                                    <th>مبلغ</th>
                                                    <th>واریز/برداشت</th>
                                                    <th>تاریخ</th>
                                                    <th>توضیحات</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var wallet in Model.SellerWallets)
                                                {
                                                    <tr>
                                                        <td>@wallet.Id</td>
                                                        <td>@wallet.Price.ToString("#,0")</td>
                                                        <td>@wallet.TransactionType.GetEnumName()</td>
                                                        <td>@wallet.CreateDate.ToShamsiDate()</td>
                                                        <td>@wallet.Description</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                        <partial name="_PagingPartial" model="@Model.GetCurrentPaging()" />
                                    }
                                    else
                                    {
                                        <partial name="_NoItemFound" />
                                    }
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>