MarketPlace.Presentation/Areas/Admin/Controllers/ProductController.cs
using MarketPlace.Application.DTOs.Common;
using MarketPlace.Application.DTOs.Products;
using MarketPlace.Application.InterfaceServices;
using MarketPlace.Presentation.Http;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Presentation.Areas.Admin.Controllers
{
    public class ProductsController : AdminBaseController
    {
        #region constructor

        private readonly IProductService _productService;

        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }

        #endregion

        #region filter products

        public async Task<IActionResult> Index(FilterProductDTO filter)
        {
            return View(await _productService.FilterProducts(filter));
        }

        #endregion

        #region accept product

        public async Task<IActionResult> AcceptSellerProduct(long id)
        {
            var result = await _productService.AcceptSellerProduct(id);
            if (result)
            {
                return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "محصول مورد نظر با موفقیت تایید شد", null);
            }

            return JsonResponseStatus.SendStatus(JsonResponseStatusType.Danger, "محصول مورد نظر یافت نشد", null);
        }

        #endregion

        #region reject product

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> RejectProduct(RejectItemDTO reject)
        {
            if (ModelState.IsValid)
            {
                var result = await _productService.RejectSellerProduct(reject);

                if (result)
                {

                    return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success,
                        "محصول مورد نظر با موفقیت رد شد", reject);
                }

                return JsonResponseStatus.SendStatus(JsonResponseStatusType.Danger, "اطلاعات مورد نظر جهت عدم تایید را به درستی وارد نمایید", null);
            }


            return JsonResponseStatus.SendStatus(JsonResponseStatusType.Danger, "محصول مورد نظر یافت نشد", null);
        }

        #endregion
    }
}

MarketPlace.Presentation/Areas/User/Controllers/SellerController.cs
using MarketPlace.Application.DTOs.Seller;
using MarketPlace.Application.InterfaceServices;
using MarketPlace.Presentation.PresentationExtensions;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Presentation.Areas.User.Controllers
{
    public class SellerController : UserBaseController
    {
        #region constructor

        private readonly ISellerService _sellerService;

        public SellerController(ISellerService sellerService)
        {
            _sellerService = sellerService;
        }

        #endregion

        #region request seller

        [HttpGet("request-seller-panel")]
        public IActionResult RequestSellerPanel()
        {
            return View();
        }

        [HttpPost("request-seller-panel"), ValidateAntiForgeryToken]
        public async Task<IActionResult> RequestSellerPanel(RequestSellerDTO seller)
        {
            if (ModelState.IsValid)
            {
                var res = await _sellerService.AddNewSellerRequest(seller, User.GetUserId());
                switch (res)
                {
                    case RequestSellerResult.HasNotPermission:
                        TempData[ErrorMessage] = "شما دسترسی لازم جهت انجام فرایند مورد نظر را ندارید";
                        break;
                    case RequestSellerResult.HasUnderProgressRequest:
                        TempData[WarningMessage] = "درخواست های قبلی شما در حال پیگیری می باشند";
                        TempData[InfoMessage] = "در حال حاضر نمیتوانید درخواست جدیدی ثبت کنید";
                        break;
                    case RequestSellerResult.Success:
                        TempData[SuccessMessage] = "درخواست شما با موفقیت ثبت شد";
                        TempData[InfoMessage] = "فرایند تایید اطلاعات شما در حال پیگیری می باشد";
                        return RedirectToAction("SellerRequests");
                }
            }

            return View(seller);
        }

        #endregion

        #region seller requests

        [HttpGet("seller-requests")]
        public async Task<IActionResult> SellerRequests(FilterSellerDTO filter)
        {
            filter.UserId = User.GetUserId();
            filter.State = FilterSellerState.All;

            return View(await _sellerService.FilterSellers(filter));
        }

        #endregion

        #region edit request

        [HttpGet("edit-request-seller/{id}")]
        public async Task<IActionResult> EditRequestSeller(long id)
        {
            var requestSeller = await _sellerService.GetRequestSellerForEdit(id, User.GetUserId());
            if (requestSeller == null) return NotFound();
            return View(requestSeller);
        }

        [HttpPost("edit-request-seller/{id}"), ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRequestSeller(EditRequestSellerDTO request)
        {
            if (ModelState.IsValid)
            {
                var res = await _sellerService.EditRequestSeller(request, User.GetUserId());
                switch (res)
                {
                    case EditRequestSellerResult.NotFound:
                        TempData[ErrorMessage] = "اطلاعات مورد نظر یافت نشد";
                        break;
                    case EditRequestSellerResult.Success:
                        TempData[SuccessMessage] = "اطلاعات مورد نظر با موفقیت ویرایش شد";
                        TempData[InfoMessage] = "فرآیند تایید اطلاعات از سر گرفته شد";
                        return RedirectToAction("SellerRequests");
                }
            }

            return View(request);
        }

        #endregion
    }
}

MarketPlace.Presentation/Areas/Admin/Views/Shared/_AdminChatBarSection.cshtml
<!-- Chat Bar -->
<div id="chatbar" class="page-chatbar">
    <div class="chatbar-contacts">
        <div class="contacts-search">
            <input type="text" class="searchinput" placeholder="Search Contacts" />
            <i class="searchicon fa fa-search"></i>
            <div class="searchhelper">Search Your Contacts and Chat History</div>
        </div>
        <ul class="contacts-list">
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/divyia.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Divyia Philips</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        last week
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/Nicolai-Larson.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Adam Johnson</div>
                    <div class="contact-status">
                        <div class="offline"></div>
                        <div class="status">left 4 mins ago</div>
                    </div>
                    <div class="last-chat-time">
                        today
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/John-Smith.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">John Smith</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        1:57 am
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/Osvaldus-Valutis.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Osvaldus Valutis</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        today
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/Javi-Jimenez.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Javi Jimenez</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        today
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/Stephanie-Walter.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Stephanie Walter</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        yesterday
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/Sergey-Azovskiy.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Sergey Azovskiy</div>
                    <div class="contact-status">
                        <div class="offline"></div>
                        <div class="status">offline since oct 24</div>
                    </div>
                    <div class="last-chat-time">
                        22 oct
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/Lee-Munroe.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Lee Munroe</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        today
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="/admin/img/avatars/divyia.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Divyia Philips</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        last week
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="chatbar-messages" style="display: none;">
        <div class="messages-contact">
            <div class="contact-avatar">
                <img src="/admin/img/avatars/divyia.jpg" />
            </div>
            <div class="contact-info">
                <div class="contact-name">Divyia Philips</div>
                <div class="contact-status">
                    <div class="online"></div>
                    <div class="status">online</div>
                </div>
                <div class="last-chat-time">
                    a moment ago
                </div>
                <div class="back">
                    <i class="fa fa-arrow-circle-left"></i>
                </div>
            </div>
        </div>
        <ul class="messages-list">
            <li class="message">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Me</div>
                    <div class="message-time">10:14 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message reply">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Divyia</div>
                    <div class="message-time">10:15 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Me</div>
                    <div class="message-time">10:14 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message reply">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Divyia</div>
                    <div class="message-time">10:15 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Me</div>
                    <div class="message-time">10:14 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message reply">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Divyia</div>
                    <div class="message-time">10:15 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
        </ul>
        <div class="send-message">
            <span class="input-icon icon-right">
                <textarea rows="4" class="form-control" placeholder="Type your message"></textarea>
                <i class="fa fa-camera themeprimary"></i>
            </span>
        </div>
    </div>
</div>
<!-- /Chat Bar -->

MarketPlace.Presentation/Areas/Admin/Views/Shared/_AdminFooterReferences.cshtml
<!--Basic Scripts-->
<script src="/admin/js/jquery.min.js"></script>
<script src="/admin/js/bootstrap.min.js"></script>
<script src="/admin/js/slimscroll/jquery.slimscroll.min.js"></script>

<!--Beyond Scripts-->
<script src="/admin/js/skins.min.js"></script>
<script src="/admin/js/beyond.min.js"></script>


<!--Page Related Scripts-->
<!--Sparkline Charts Needed Scripts-->
<script src="/admin/js/charts/sparkline/jquery.sparkline.js"></script>
<script src="/admin/js/charts/sparkline/sparkline-init.js"></script>

<!--Easy Pie Charts Needed Scripts-->
<script src="/admin/js/charts/easypiechart/jquery.easypiechart.js"></script>
<script src="/admin/js/charts/easypiechart/easypiechart-init.js"></script>

<!--Flot Charts Needed Scripts-->
<script src="/admin/js/charts/flot/jquery.flot.js"></script>
<script src="/admin/js/charts/flot/jquery.flot.resize.js"></script>
<script src="/admin/js/charts/flot/jquery.flot.pie.js"></script>
<script src="/admin/js/charts/flot/jquery.flot.tooltip.js"></script>
<script src="/admin/js/charts/flot/jquery.flot.orderBars.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>
<script src="/js/notifications.js"></script>
<script src="/admin/js/custom.js"></script>

<script>

    //Sets The Hidden Chart Width
    $('#dashboard-bandwidth-chart')
    .data('width', $('.box-tabbs')
    .width() - 20);
    //Visitor Sources Pie Chart
    var data = [
    {
    data: [[1, 21]],
    color: '#fb6e52'
    },
    {
    data: [[1, 12]],
    color: '#e75b8d'
    },
    {
    data: [[1, 11]],
    color: '#a0d468'
    },
    {
    data: [[1, 10]],
    color: '#ffce55'
    },
    {
    data: [[1, 46]],
    color: '#5db2ff'
    }
    ];
    var placeholder = $("#dashboard-pie-chart-sources");
    placeholder.unbind();

    $.plot(placeholder, data, {
    series: {
    pie: {
    innerRadius: 0.45,
    show: true,
    stroke: {
    width: 4
    }
    }
    }
    });

    //Visit Chart (Main Chart)
    var data2 = [{
    color: themesecondary,
    label: "بازدید مستقیم",
    data: [[3, 2], [4, 5], [5, 4], [6, 11], [7, 12], [8, 11], [9, 8], [10, 14], [11, 12], [12, 16], [13, 9],
    [14, 10], [15, 14], [16, 15], [17, 9]],

    lines: {
    show: true,
    fill: true,
    lineWidth: .1,
    fillColor: {
    colors: [{
    opacity: 0
    }, {
    opacity: 0.4
    }]
    }
    },
    points: {
    show: false
    },
    shadowSize: 0
    },
    {
    color: themeprimary,
    label: "لینک از سایتها",
    data: [[3, 10], [4, 13], [5, 12], [6, 16], [7, 19], [8, 19], [9, 24], [10, 19], [11, 18], [12, 21], [13, 17],
    [14, 14], [15, 12], [16, 14], [17, 15]],
    bars: {
    order: 1,
    show: true,
    borderWidth: 0,
    barWidth: 0.4,
    lineWidth: .5,
    fillColor: {
    colors: [{
    opacity: 0.4
    }, {
    opacity: 1
    }]
    }
    }
    },
    {
    color: themethirdcolor,
    label: "موتورهای جستجو",
    data: [[3, 14], [4, 11], [5, 10], [6, 9], [7, 5], [8, 8], [9, 5], [10, 6], [11, 4], [12, 7], [13, 4],
    [14, 3], [15, 4], [16, 6], [17, 4]],
    lines: {
    show: true,
    fill: false,
    fillColor: {
    colors: [{
    opacity: 0.3
    }, {
    opacity: 0
    }]
    }
    },
    points: {
    show: true
    }
    }
    ];
    var options = {
    legend: {
    show: false
    },
    xaxis: {
    tickDecimals: 0,
    color: '#f3f3f3'
    },
    yaxis: {
    min: 0,
    color: '#f3f3f3',
    tickFormatter: function (val, axis) {
    return "";
    },
    },
    grid: {
    hoverable: true,
    clickable: false,
    borderWidth: 0,
    aboveData: false,
    color: '#fbfbfb'

    },
    tooltip: true,
    tooltipOpts: {
    defaultTheme: false,
    content: " <b>%x تیر ماه</b> , <b>%s</b> : <span>%y</span>",
    }
    };
    var placeholder = $("#dashboard-chart-visits");
    var plot = $.plot(placeholder, data2, options);

    //Real-Time Chart
    var realTimedata = [],
    realTimedata2 = [],
    totalPoints = 300;

    var getSeriesObj = function () {
    return [
    {
    data: getRandomData(),
    lines: {
    show: true,
    lineWidth: 1,
    fill: true,
    fillColor: {
    colors: [
    {
    opacity: 0
    }, {
    opacity: 1
    }
    ]
    },
    steps: false
    },
    shadowSize: 0
    }, {
    data: getRandomData2(),
    lines: {
    lineWidth: 0,
    fill: true,
    fillColor: {
    colors: [
    {
    opacity: .5
    }, {
    opacity: 1
    }
    ]
    },
    steps: false
    },
    shadowSize: 0
    }
    ];
    };
    function getRandomData() {
    if (realTimedata.length > 0)
    realTimedata = realTimedata.slice(1);

    // Do a random walk

    while (realTimedata.length < totalPoints) {

    var prev = realTimedata.length > 0 ? realTimedata[realTimedata.length - 1] : 50,
    y = prev + Math.random() * 10 - 5;

    if (y < 0) {
    y = 0;
    } else if (y > 100) {
    y = 100;
    }
    realTimedata.push(y);
    }

    // Zip the generated y values with the x values

    var res = [];
    for (var i = 0; i < realTimedata.length; ++i) {
    res.push([i, realTimedata[i]]);
    }

    return res;
    }
    function getRandomData2() {
    if (realTimedata2.length > 0)
    realTimedata2 = realTimedata2.slice(1);

    // Do a random walk

    while (realTimedata2.length < totalPoints) {

    var prev = realTimedata2.length > 0 ? realTimedata[realTimedata2.length] : 50,
    y = prev - 25;

    if (y < 0) {
    y = 0;
    } else if (y > 100) {
    y = 100;
    }
    realTimedata2.push(y);
    }


    var res = [];
    for (var i = 0; i < realTimedata2.length; ++i) {
    res.push([i, realTimedata2[i]]);
    }

    return res;
    }
    // Set up the control widget
    var updateInterval = 500;
    var plot = $.plot("#dashboard-chart-realtime", getSeriesObj(), {
    yaxis: {
    color: '#f3f3f3',
    min: 0,
    max: 100,
    tickFormatter: function (val, axis) {
    return "";
    }
    },
    xaxis: {
    color: '#f3f3f3',
    min: 0,
    max: 100,
    tickFormatter: function (val, axis) {
    return "";
    }
    },
    grid: {
    hoverable: true,
    clickable: false,
    borderWidth: 0,
    aboveData: false
    },
    colors: ['#eee', themeprimary],
    });

    function update() {

    plot.setData(getSeriesObj());

    plot.draw();
    setTimeout(update, updateInterval);
    }
    update();


    //Initiates Easy Pie Chart instances in page
    InitiateEasyPieChart.init();

    //Initiates Sparkline Chart instances in page
    InitiateSparklineCharts.init();
</script>

MarketPlace.Presentation/Areas/Admin/Views/Shared/_AdminHeaderReferences.cshtml
<link rel="shortcut icon" href="/admin/img/favicon.png" type="image/x-icon">

<!--Basic Styles-->
<link href="/admin/css/bootstrap.min.css" rel="stylesheet" />
<link href="/admin/css/bootstrap-rtl.min.css" rel="stylesheet" />
<link href="/admin/css/font-awesome.min.css" rel="stylesheet" />
<link href="/admin/css/weather-icons.min.css" rel="stylesheet" />

<!--Fonts-->
<style>
    @@font-face {
        font-family: 'WYekan';
        src: url('/admin/fonts/BYekan.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }
</style>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">

<!--Beyond styles-->
<link href="/admin/css/beyond-rtl.min.css" rel="stylesheet" />
<link href="/admin/css/4095-rtl.min.css" rel="stylesheet" type="text/css" />
<link href="/admin/css/demo.min.css" rel="stylesheet" />
<link href="/admin/css/typicons.min.css" rel="stylesheet" />
<link href="/admin/css/animate.min.css" rel="stylesheet" />
<link href="/admin/css/custom.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="/css/notifications.css">
<link id="skin-link" href="" rel="stylesheet" type="text/css" />

MarketPlace.Presentation/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<!--
BeyondAdmin - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.6
Version: 1.6.0
Purchase: https://wrapbootstrap.com/theme/beyondadmin-adminapp-angularjs-mvc-WB06R48S4
-->

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="description" content="Dashboard" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <partial name="_AdminHeaderReferences" />
    @RenderSection("styles", false)
</head>
<body>
    <div class="loading-container">
        <div class="loader"></div>
    </div>
    <partial name="_AdminNaveBarSection" />
    <div class="main-container container-fluid">
        <div class="page-container">
                <partial name="_AdminSideBarSection"></partial>
                <partial name="_AdminChatBarSection"></partial>
            <div class="page-content">
                <!-- Page Breadcrumb -->
                <div class="page-breadcrumbs">
                    <ul class="breadcrumb">
                        <li>
                            <i class="fa fa-home"></i>
                            <a asp-area="Admin" asp-controller="Home" asp-action="Index">خانه</a>
                        </li>
                        @RenderSection("breadcrumb",false)
                        <li class="active">@ViewData["Title"]</li>
                    </ul>
                </div>
                <!-- /Page Breadcrumb -->
                <!-- Page Header -->
                <div class="page-header position-relative">
                    <div class="header-title">
                        <h1>
                            @ViewData["Title"]
                        </h1>
                    </div>
                    <!--Header Buttons-->
                    <div class="header-buttons">
                        <a class="sidebar-toggler" href="#">
                            <i class="fa fa-arrows-h"></i>
                        </a>
                        <a class="refresh" id="refresh-toggler" href="">
                            <i class="glyphicon glyphicon-refresh"></i>
                        </a>
                        <a class="fullscreen" id="fullscreen-toggler" href="#">
                            <i class="glyphicon glyphicon-fullscreen"></i>
                        </a>
                    </div>
                    <!--Header Buttons End-->
                </div>
                <!-- /Page Header -->
                <!-- Page Body -->
                <div class="page-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <partial name="_AdminFooterReferences" />
    @RenderSection("scripts", false)
</body>
</html>

MarketPlace.Presentation/Areas/Admin/Views/Shared/_AdminPagingPartial.cshtml
@model MarketPlace.Application.DTOs.Paging.BasePaging


<ul class="pagination">
    @if (Model.StartPage < Model.PageId)
    {
        <li class="cursor-pointer"><a onclick="FillPageId(@(Model.PageId - 1))">«</a></li>
    }

    @for (int i = Model.StartPage; i <= Model.EndPage; i++)
    {
        <li class="@(Model.PageId == i ? "active":"") cursor-pointer"><a onclick="FillPageId(@i)">@i<span class="sr-only">(current)</span></a></li>
    }

    @if (Model.EndPage > Model.PageId)
    {
        <li class="cursor-pointer"><a onclick="FillPageId(@(Model.PageId + 1))">»</a></li>
    }
</ul>

MarketPlace.Presentation/Areas/Admin/Views/Shared/_AdminSideBarSection.cshtml
<!-- Page Sidebar -->
<div class="page-sidebar" id="sidebar">
    <!-- Page Sidebar Header-->
    <div class="sidebar-header-wrapper">
        <input type="text" class="searchinput" />
        <i class="searchicon fa fa-search"></i>
        <div class="searchhelper">به جستجوی صفحات، گزارشات، پیام ها و ایمیل خود بپردازید</div>
    </div>
    <!-- /Page Sidebar Header -->
    <!-- Sidebar Menu -->
    <ul class="nav sidebar-menu">
        <!--Dashboard-->
        <li>
            <a asp-area="Admin" asp-controller="Home" asp-action="Index">
                <i class="menu-icon glyphicon glyphicon-home"></i>
                <span class="menu-text"> داشبورد </span>
            </a>
        </li>

        <!--UI Elements-->
        <li>
            <a href="#" class="menu-dropdown">
                <i class="menu-icon fa fa-user"></i>
                <span class="menu-text"> مدیریت فروشندگان </span>

                <i class="menu-expand"></i>
            </a>

            <ul class="submenu">
                <li>
                    <a asp-area="Admin" asp-controller="Seller" asp-action="SellerRequests">
                        <span class="menu-text">درخواست های فروشندگی</span>
                    </a>
                </li>
            </ul>
        </li>

        <!--UI Elements-->
        <li>
            <a href="#" class="menu-dropdown">
                <i class="menu-icon fa fa-user"></i>
                <span class="menu-text"> مدیریت محصولات </span>

                <i class="menu-expand"></i>
            </a>

            <ul class="submenu">
                <li>
                    <a asp-area="Admin" asp-controller="Products" asp-action="Index">
                        <span class="menu-text">لیست محصولات</span>
                    </a>
                </li>
            </ul>
        </li>

    </ul>
    <!-- /Sidebar Menu -->
</div>
<!-- /Page Sidebar -->

MarketPlace.Presentation/Areas/Admin/Views/Shared/_RejectItemPartial.cshtml
@model MarketPlace.Application.DTOs.Common.RejectItemDTO
<input type="hidden" asp-for="Id" />
<div class="form-group">
    <label for="definpu">متن مورد نظر</label>
    <textarea class="form-control" asp-for="RejectMessage" rows="10"></textarea>
    <span class="text-danger" asp-validation-for="RejectMessage"></span>
</div>